IndrivoFinal/Controllers/LoginHistoryController.cs
using IndrivoFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IndrivoFinal.Controllers
{
    [Authorize(Roles = RoleName.AdminRole)]
    public class LoginHistoryController : Controller
    {
        private ApplicationDbContext _context;

        public LoginHistoryController()
        {
            _context = new ApplicationDbContext();
        }

        public ViewResult Index()
        {
            var loginHistory = _context.LoginHistories.ToList();
            return View(loginHistory);
        }
    }
}

IndrivoFinal/Controllers/UsersController.cs
using IndrivoFinal.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IndrivoFinal.Controllers
{
    [Authorize(Roles = RoleName.AdminRole)]
    public class UsersController : Controller
    {
        private ApplicationDbContext _application;


        public UsersController()
        {
            _application = new ApplicationDbContext();
        }

        public UsersController(ApplicationDbContext application)
        {
            _application = application;
        }

        public ActionResult Index()
        {

            return View(_application.Users.ToList());
        }
    }
}

IndrivoFinal/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<div style="background-color: #969892; color: White; height: 10px;">
</div>
<div style="background-color: black; color: White; height: 170px;">
    <div style=" padding:20px;">
        <h2>
            This is my custom 404 NOT FOUND Page
        </h2>

        <h3>
            Application Error:
        </h3>
        <h4>
            Sorry, The Page, You are Looking for is not found.
        </h4>
        <h6 style="color:gray">@Html.ActionLink("Go Back To Home Page", "Index", "Home")</h6>
        <br />
        <br />
    </div>
</div>
<div style="background-color: #969892; color: White; height: 20px;">
</div>

IndrivoFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if (User.IsInRole("AdminRole"))
    {
        @Html.Partial("_NavBar")
    }
    else
    {
        @Html.Partial("_NavBarForSimpleUsers")
    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Indrivo</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/lib")

    @RenderSection("scripts", required: false)
</body>
</html>

IndrivoFinal/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Indrivo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("All Users", "Index", "Users")</li>
                <li>@Html.ActionLink("Login History", "Index", "LoginHistory")</li>
                <li>@Html.ActionLink("Profile Settings", "UpdateProfile", "Manage")</li>
                <li>@Html.ActionLink("Change Password", "ChangePassword", "Manage")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

IndrivoFinal/Views/Shared/_NavBarForSimpleUsers.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Indrivo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Profile Settings", "UpdateProfile", "Manage")</li>
                <li>@Html.ActionLink("Change Password", "ChangePassword", "Manage")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>